### ISSUE TITLE
Application crash while run into device!

### ISSUE THREAD

**Issue by amits180891** [anandmuralidhar24/CornerDetectAndroid#1]
Get issue/crash while launch app. Successfully import the project but when i launched the app app crash on  static {
        System.loadLibrary("CornerNative");
    }

 inside the CornerDetectActivity.class line no. 124.

Log :
```
 Process: com.anandmuralidhar.cornerdetectandroid, PID: 11833
                                                                                         java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.anandmuralidhar.cornerdetectandroid-2/base.apk"],nativeLibraryDirectories=[/data/app/com.anandmuralidhar.cornerdetectandroid-2/lib/arm, /system/fake-libs, /data/app/com.anandmuralidhar.cornerdetectandroid-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libCornerNative.so"
```

how can i resolve that crash or where i found that lib.

**Comment by anandmuralidhar24** [comment]
Looks like the library is not getting built for your phone. Can you let me know your device,ABI, and android version?
The project will run on devices with ABI armeabi-v7a and will fail on other ABIs.

**Comment by amits180891** [comment]
Hello Sir,

Thanks for the  replay.

I am using MOTO-Z force droid phone,android  android version 7.1.1.

App crash on launch screen.

Thanks.

On Fri, Dec 22, 2017 at 12:05 PM, Anand Muralidhar <notifications@github.com

**Comment by anandmuralidhar24** [comment]
That lib will be built when you compile the code. Can you check the ABI of the device is armeabi-v7a, else the project will not run.

**Comment by amits180891** [comment]
My device ABI  - armeabi-v7a.

I have found that ABI version programmatically : 

 String ABI = Build.SUPPORTED_ABIS[0];
Log.e( "onCreate: ","ABI===="+ ABI );

Log print : 
E/onCreate:: ABI====armeabi-v7a

**Comment by anandmuralidhar24** [comment]
Thanks for confirming that.
Then its a strange problem since the project should run on the devices. I'm not sure what is causing the error. Maybe the lib did not get built the first time. Did you try doing a clean build? I have tested till Android 6 and am not sure if there are any new dependencies in Android 7+.

**Comment by amits180891** [comment]
Can you please give me proper solution for that?

 Can you please share an updated apk file or share code which worked on Android 6 ?

I am not updating the code. Use the same code on old studio as well. not updated any gradle or target sdk versions.

I have share code with you. Can you please check this & let me know what i have done wrong from my side.

Drive url : https://drive.google.com/file/d/1xDLnh4xK-RaWZ2Uy2Bc6WITu5Eim_Xxj/view?usp=sharing

**Comment by amits180891** [comment]
Hello Sir,

Have you check my code? 
Can you please share an apk which work properly in all devices, So i can easily resolve my problem using that apk reference.

Please check my build i have share with you :

https://drive.google.com/file/d/19evmeZ68oFk6qHxQSa8RPL4cOBq664df/view?usp=sharing

**Comment by amits180891** [comment]
Can you please share **`libCornerNative.so`** file. So i can try to add manually to resolve that issue?

**Comment by anandmuralidhar24** [comment]
Hi Amit,
I can't share a code that works on all devices. As I said it needs devices
with certain abis. I'm not sure about the issue that you are facing since
I've not seen this problem previously.
Best,
Anand

**Comment by amits180891** [comment]
Thanks you sir for reply!

Can you please help me, how can i replace the red dot with image or gif  ?

**Comment by anandmuralidhar24** [comment]
you will need to use the gravity vector to align the image/gif along the plane on the floor. you need to understand how the project works in detail so that you can make the required changes.
